s3:
  short: "&S3;"
  long: "&S3long;"
  expanded:
    long: Amazon Simple Storage Service (Amazon S3)
    short: Amazon S3
  sort: "S3"
  version: s3-2006-03-01
  caveat: The examples in this section are pretty neat, and we recommend you print them out so you can
    read them in bed with a good glass of wine.
  api_ref: AmazonS3/latest/API/Welcome.html
  blurb: is storage for the internet. You can use Amazon S3 to store and retrieve any amount of data at any time, from anywhere on the web.
  guide:
    subtitle: User Guide
    url: AmazonS3/latest/userguide/Welcome.html
medical-imaging:
  short: "&AHI;"
  long: "&AHIlong;"
  expanded:
    long: AWS HealthImaging
    short: HealthImaging
  sort: "HealthImaging"
  version: medical-imaging-2023-07-19
sqs:
  short: "&SQS;"
  long: "&SQSlong;"
  api_client: "test_sqs_api_client"
  expanded:
    long: Amazon Simple Queue Service (Amazon SQS)
    short: Amazon SQS
  sort: "SQS"
  tags:
    product_categories: {'Category 1', 'Category 2'}
  version: sqs-2012-11-05
  bundle: sqs
textract:
  short: "&TEXTRACT;"
  long: "&TEXTRACTlong;"
  expanded:
    long: Amazon Textract
    short: Amazon Textract
  sort: "Textract"
  tags:
    product_categories: {'Category 1'}
  version: textract-2018-06-27
